import Base
import ./LAWS.bend as Laws

def Laws.verified_is_zero(amount):
  {==}

def Laws.high_is_95():
  {==}

def Laws.low_is_10():
  {==}

def Laws.bounded(over, verified):
  match over:
    case True{}:
      match verified:
        case True{}:
          {==}
        case False{}:
          {==}
    case False{}:
      match verified:
        case True{}:
          {==}
        case False{}:
          {==}

def Laws.threshold_is_inclusive():
  {==}

def Laws.first_cent_above():
  {==}
